# Generated by Django 3.2.9 on 2022-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220115_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
    ]
