# Generated by Django 3.2.9 on 2022-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_value_measurement_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
